name: mecapan_technical_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.3.1
  connectivity: ^0.4.9+3
  cupertino_icons: ^1.0.0
  flutter_platform_widgets: ^0.70.2
  get: ^3.13.2
  get_it: ^5.0.1
  http: ^0.12.2
  logger: ^0.9.4
  pedantic: ^1.9.2
  stacked: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
